apiVersion: v1
kind: Service
metadata:
  name: k8s-web-hello-to-nginx
spec:
  selector:
    app: k8s-web-hello-to-nginx
  ports:
  - port: 3333
    targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-web-hello-to-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-web-hello-to-nginx
  template:
    metadata:
      labels:
        app: k8s-web-hello-to-nginx
    spec:
      containers:
      - name: k8s-web-hello-to-nginx
        image: zull123/kubernetes-node-to-nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 3000